version: '3.8'

services:  
  cpe-lm:    
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    container_name: cpe-lm    
    volumes:     
      - ./src:/home/node/app/src      
      - ./nodemon.json:/home/node/app/nodemon.json
    expose:
      - '49090'
    ports:
      - '49090:49090'
    command: npm run dev
