version: '3.8'
services:  
  api:    
    build: ./docer   
    container_name: api_backend    
    ports:      
      - '4000:4000'    
    volumes:     
      - ./dist:/dist      
      - ./app/node_modules